import './components/form-component.js'
import './components/header-component.js'
import './components/table-component.js'
import './components/title-component.js'
import './components/menu-component.js'
import './components/main-component.js'
import './components/page-component.js'
