const express = require('express')
const router = express.Router()

router.use('/admin/users', require('./admin/users'))
router.use('/admin/customers', require('./admin/customers'))
router.use('/admin/bots', require('./admin/bots'))
router.use('/admin/faqs', require('./admin/faqs'))
router.use('/admin/event-categories', require('./admin/event-categories'))
router.use('/admin/promoters', require('./admin/promoters'))
router.use('/admin/user-credentials', require('./admin/user-credentials'))
router.use('/admin/customers', require('./admin/customers'))
router.use('/admin/spots', require('./admin/spots'))
router.use('/admin/promoters-spots', require('./admin/promoters-spots'))
router.use('/admin/emails', require('./admin/emails'))
router.use('/admin/email-errors', require('./admin/email-errors'))
router.use('/admin/sent-emails', require('./admin/sent-emails'))
router.use('/admin/languages', require('./admin/languages'))
router.use('/admin/towns', require('./admin/towns'))
router.use('/admin/events', require('./admin/events'))
router.use('/admin/event-prices', require('./admin/event-prices'))
router.use('/admin/event-occurrences', require('./admin/event-occurrences'))
router.use('/admin/customers-events', require('./admin/customers-events'))
router.use('/admin/customers-bots', require('./admin/customers-bots'))
router.use('/admin/customer-bot-chats', require('./admin/customer-bot-chats'))

module.exports = router
